### ISSUE TITLE
Datatable Improvements Overview

### ISSUE THREAD

**Issue by jaclarke** [edgedb/edgedb-ui#331]
- [ ] Refactor datatable so we can render query results in table format (#275)
- [ ] Keyboard navigation
- [ ] Data copy/export + row selection (see #65)
- [ ] #212
- [ ] Consider removing inline inspector for expanded row, and replace with sidepanel view. Would be more consistent with mobile view, allow more space for field editing, and I think play better with keyboard navigation.

Columns:
- [ ] Re-order columns (#268)
- [ ] Select/hide columns
  - Replaces current 'show subtype fields' toggle
  - Have way to easily select all props/links/subtypes/computeds? (#308)
- [ ] Pinned columns (#321)
